### ISSUE TITLE
Demo: Find one more news source

### ISSUE THREAD

**Issue by jaygoodswp** [TMM21042/PHS#56]

**Comment by jaygoodswp** [comment]
This has been completed and will be in the next release.

**Comment by TMM21042** [comment]
HI Jay; I tested the Reuters RSS feed and it seems to work. They have multiple feeds and I think the top news or USA news feeds would work fine.



Sent from my mobile device with auto complete technology. Please forgive incorrect grammar.

---- jaygoodswp wrote ----

**Comment by jaygoodswp** [comment]
OK, I'll check these out as well.  I added BBC.
